export type ContentBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "quote"; text: string }

export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  date: string
  dateFormatted: string
  author: string
  authorRole: string
  category: string
  tags: string[]
  image: string
  readTime: number
  content: ContentBlock[]
}

const u = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&h=630&q=85`

export const posts: BlogPost[] = [
  // Ronda 1 ─────────────────────────────────────────────────────────────────
  {
    slug: "por-que-me-despierto-a-las-3am",
    title: "Las 3 de la madrugada: por qué tu cerebro te despierta (y cómo volver a dormir)",
    excerpt: "Despertar en mitad de la noche y no poder volver a dormirte es más común de lo que crees. Aquí explicamos qué está pasando en tu cuerpo — y qué puedes hacer.",
    date: "2026-04-20",
    dateFormatted: "20 de abril de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Sueño",
    tags: ["insomnio", "sueño fragmentado", "despertar nocturno", "ritmo circadiano"],
    image: u("1541480601022-2308c0f02487"),
    readTime: 6,
    content: [
      { type: "p", text: "Ya sé qué hora es. No necesitas mirar el teléfono — el cuerpo lo sabe antes que tú. Son las 3, o las 3 y algo, y estás completamente despierto sin haber decidido estarlo." },
      { type: "p", text: "Lo frustrante no es el despertar. Es lo que viene después: la mente que se enciende sola, el repaso mental de todo lo pendiente, la cuenta regresiva de cuántas horas quedan antes de que suene la alarma. Y la certeza — esa certeza horrible — de que esta noche tampoco vas a dormir bien." },
      { type: "h2", text: "El sueño no es un interruptor" },
      { type: "p", text: "Tendemos a pensar en el sueño como algo que se enciende y se apaga. Pero en realidad es una secuencia de ciclos de unos 90 minutos, y cada ciclo termina con un momento de sueño más ligero — casi una pequeña pausa — antes de entrar al siguiente. El despertar a las 3 a.m. suele coincidir justo con una de esas pausas. La mayoría de las noches, la transición es tan suave que ni la notas. Pero cuando el cuerpo está bajo estrés sostenido, cuando el cortisol empieza a subir antes de tiempo, o cuando hay algo perturbando la arquitectura del sueño, esa pequeña pausa se convierte en un agujero por el que te caes." },
      { type: "h2", text: "El cortisol no es tu enemigo. Solo llega demasiado temprano" },
      { type: "p", text: "El cortisol es la hormona que te prepara para el día. Normalmente empieza a subir alrededor de las 5 o 6 de la mañana. Pero en personas con estrés crónico, ansiedad, o el ritmo circadiano desajustado, ese pico llega antes — a las 3, a las 4 — y el cuerpo interpreta la señal como: ya es de día, hay que funcionar. No es que no puedas dormir. Es que tu reloj interno está adelantado. Otras causas frecuentes: una caída de azúcar en sangre a mitad de la noche, una habitación demasiado cálida, o el alcohol de la cena que fragmenta los ciclos justo en la segunda mitad del sueño." },
      { type: "quote", text: "El problema no siempre es quedarte dormido. A veces es quedarte dormido después de despertar. Y eso tiene causas muy específicas que se pueden abordar." },
      { type: "h2", text: "Lo que no funciona, aunque parezca lógico" },
      { type: "p", text: "Revisar el teléfono. Mirar la hora. Levantarte a comer algo. Ponerte a planear lo de mañana 'ya que estás despierto de todas formas'. Todo eso le confirma al cerebro que las 3 a.m. es un momento de actividad. Y el cerebro aprende rápido: en pocas semanas, lo que era un despertar ocasional se convierte en hábito. El cuerpo empieza a esperarlo." },
      { type: "h2", text: "Cuándo preocuparse de verdad" },
      { type: "p", text: "Un mal sueño puntual no es nada. Tres semanas seguidas despertando a la misma hora, con cansancio acumulado, el humor y la concentración afectados — eso ya merece atención. El sueño fragmentado crónico no es solo cansancio: eleva marcadores inflamatorios, altera el metabolismo, y tiene efectos sobre el estado de ánimo que a veces se confunden con ansiedad o depresión. La buena noticia es que casi siempre hay una causa identificable. Y si hay una causa, hay algo que hacer." },
    ],
  },
  {
    slug: "cuando-el-dolor-no-tiene-explicacion",
    title: "Cuando el dolor no tiene explicación: qué hacer si tus exámenes salen normales",
    excerpt: "Tener dolor real con exámenes normales no significa que estés inventándotelo. Significa que el sistema médico convencional aún no encontró la causa — y eso tiene solución.",
    date: "2026-04-13",
    dateFormatted: "13 de abril de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Dolor Crónico",
    tags: ["dolor crónico", "fibromialgia", "diagnóstico", "medicina integrativa"],
    image: u("1571019613454-1cb2f99b2d8b"),
    readTime: 7,
    content: [
      { type: "p", text: "\"Sus exámenes están normales.\" Para alguien que lleva meses con dolor, esa frase debería ser un alivio. Pero no lo es. Porque la conclusión implícita — la que nadie dice pero todos entienden — es: entonces el problema está en tu cabeza." },
      { type: "p", text: "No está en tu cabeza. O bueno, sí está en tu cabeza, en el sentido de que todo dolor ocurre en el sistema nervioso. Pero eso no significa que sea inventado. Significa que los exámenes de rutina no están mirando en el lugar correcto." },
      { type: "h2", text: "El problema con 'normal'" },
      { type: "p", text: "La medicina convencional es extraordinariamente buena para detectar daño estructural: fracturas, tumores, inflamación aguda visible en imágenes. Pero el dolor crónico frecuentemente ocurre sin daño estructural visible. La fibromialgia, el síndrome de sensibilización central, el dolor miofascial, el dolor neuropático — todas son condiciones reales, con décadas de investigación detrás, que no aparecen en una resonancia ni en una analítica de sangre estándar. Un examen normal no descarta el dolor. Solo descarta ciertas causas del dolor." },
      { type: "h2", text: "Señales de que podrías estar ante dolor crónico no diagnosticado" },
      { type: "ul", items: [
        "Dolor que se mueve o cambia de lugar sin razón aparente",
        "Fatiga que no mejora con descanso, aunque hayas dormido bien",
        "Hipersensibilidad rara: la ropa roza, la luz molesta, los ruidos irritan más de lo habitual",
        "Varios síntomas 'sin relación': intestino, cefaleas, sueño, dolor — todo junto",
        "Empeora con el estrés o con unos días de mal sueño",
        "Varios médicos, varios diagnósticos distintos, ninguno que termine de encajar",
      ]},
      { type: "quote", text: "El dolor es siempre real. Si lo sientes, existe. El trabajo médico es encontrar su origen — no descartarlo porque no aparezca en los exámenes de rutina." },
      { type: "h2", text: "Buscar el sistema, no solo el síntoma" },
      { type: "p", text: "Un enfoque integrativo del dolor crónico no busca la lesión en la imagen: busca el patrón en el sistema. El sistema nervioso, el sistema inmune, el microbioma, los patrones de sueño, el estado nutricional, la carga de estrés sostenido. El dolor sin explicación casi siempre tiene múltiples causas que se potencian entre sí. Cuando se abordan en conjunto — en lugar de una a la vez, en consultas separadas — los pacientes encuentran alivio que nunca tuvieron tratando solo una pieza del rompecabezas." },
      { type: "p", text: "Si llevas tiempo con dolor que nadie ha sabido explicar, no normalices. No es que seas especialmente sensible ni que tengas mala suerte. Hay algo que está pasando — y merece una evaluación que lo busque de verdad." },
    ],
  },
  {
    slug: "ansiedad-vs-estres-como-diferenciarlos",
    title: "Ansiedad o estrés: cómo diferenciarlos y por qué importa la distinción",
    excerpt: "\"Son los nervios\" o \"es el trabajo\" — la ansiedad se disfraza de estrés cotidiano durante años. Entender la diferencia puede cambiar completamente cómo la abordas.",
    date: "2026-04-06",
    dateFormatted: "6 de abril de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Ansiedad",
    tags: ["ansiedad", "estrés", "salud mental", "bienestar emocional"],
    image: u("1507003211169-0a1dd7228f2d"),
    readTime: 5,
    content: [
      { type: "p", text: "\"Estoy muy estresado\" es probablemente la frase que más se escucha en consulta. Y tiene sentido: el estrés es una explicación que lo justifica todo y que además no asusta. Es socialmente aceptable, incluso admirado. Estar estresado significa que estás ocupado, que te importa, que eres productivo." },
      { type: "p", text: "El problema es que a veces eso que llamamos estrés tiene otro nombre. Y ese otro nombre implica un mecanismo diferente — y un abordaje diferente." },
      { type: "h2", text: "La diferencia que cambia todo" },
      { type: "p", text: "El estrés tiene un origen claro: la reunión de mañana, la deuda, el conflicto con tu pareja. Cuando ese factor desaparece o se resuelve, el estrés baja. Lo notas. La ansiedad no funciona así. Persiste cuando el factor externo ya no está. Salta de una preocupación a otra sin que ninguna se resuelva del todo. O peor: aparece sin ninguna razón concreta, como una alarma que suena aunque no haya humo. El cerebro ansioso no necesita una razón real para activarse. Crea las suyas." },
      { type: "h2", text: "Señales de que puede ser ansiedad y no solo estrés" },
      { type: "ul", items: [
        "Te preocupas de forma desproporcionada por cosas que 'racionalmente' sabes que no son graves",
        "Tensión muscular crónica en cuello, mandíbula u hombros que no recuerdas cuándo empezó",
        "No puedes dejar de pensar cuando intentas dormirte",
        "Sensación constante de urgencia o apuro, aunque no haya nada urgente",
        "Irritabilidad que no corresponde a lo que pasó ese día",
        "Palpitaciones, mareos o dificultad para respirar que el médico dice que 'no son nada'",
        "Evitas cosas o compromisos porque anticipas que algo saldrá mal",
      ]},
      { type: "quote", text: "La ansiedad no llega con un cartel. Se instala de a poco, disfrazada de 'soy muy exigente' o 'tengo mucho en la cabeza', hasta que un día te das cuenta de que llevas años sin estar tranquilo." },
      { type: "h2", text: "Por qué la distinción importa tanto" },
      { type: "p", text: "Si lo tuyo es estrés situacional, manejar los tiempos, poner límites y descansar activo puede ser suficiente. Si lo tuyo es ansiedad — una activación sostenida del sistema nervioso que ya no depende de los eventos externos — esas mismas herramientas ayudan poco sin abordar la fisiología que la sostiene. No es que seas débil ni que debas 'relajarte más'. Es que hay algo en tu sistema nervioso que está en alerta permanente, y eso tiene solución." },
    ],
  },
  {
    slug: "spm-severo-no-es-normal",
    title: "SPM severo: cuando tu ciclo te tumba y te dicen que \"es normal\"",
    excerpt: "No es dramatismo ni falta de carácter. El síndrome premenstrual severo es una condición médica real — y decirte que \"todas las mujeres lo tienen\" no es una respuesta suficiente.",
    date: "2026-03-30",
    dateFormatted: "30 de marzo de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Salud Femenina",
    tags: ["SPM", "síndrome premenstrual", "salud femenina", "ciclo menstrual"],
    image: u("1554151228-14d9def656e4"),
    readTime: 6,
    content: [
      { type: "p", text: "Hay una semana al mes — a veces diez días — en que no te reconoces. El humor se va al piso sin previo aviso. El cuerpo duele de una forma difícil de explicar. La irritabilidad es tan intensa que tú misma te asustas. Y cuando intentas contarlo, alguien dice: \"es que todas somos así antes de la regla\"." },
      { type: "p", text: "No. No todas son así. Y aunque algunas molestias premenstruales sean comunes, hay un punto en que dejan de ser normales — y ese punto es cuando interfieren con tu vida." },
      { type: "h2", text: "SPM y TDPM: no es lo mismo" },
      { type: "p", text: "El síndrome premenstrual afecta a muchas mujeres con síntomas leves o moderados que son manejables. Pero existe una forma severa llamada Trastorno Disfórico Premenstrual — TDPM — que es otra cosa. Disforia intensa, llanto sin causa aparente, irritabilidad que puede arruinar relaciones, pensamientos que asustan. Todo eso aparece de forma predecible en la segunda mitad del ciclo y desaparece con la menstruación. No es carácter. No es dramatismo. Es una respuesta hormonal desproporcionada con mecanismos neurobiológicos identificables." },
      { type: "h2", text: "Señales de que tu SPM merece atención médica" },
      { type: "ul", items: [
        "Los síntomas aparecen y desaparecen de forma cíclica y predecible",
        "Afectan tu trabajo, tus relaciones o tu capacidad de hacer cosas cotidianas",
        "Tú misma percibes que 'no eres tú' en esos días",
        "El dolor físico — senos, hinchazón, cabeza — es intenso y no cede fácilmente",
        "Llevas años adaptando tu vida alrededor de esa semana",
      ]},
      { type: "quote", text: "Muchas mujeres llegan a consulta con 35 o 40 años habiendo normalizado algo que podría haberse abordado mucho antes. El tiempo que se perdió no vuelve, pero el alivio sí es posible." },
      { type: "h2", text: "Qué incluye un abordaje real" },
      { type: "p", text: "No una pastilla para el dolor el día que duele. Un abordaje real del SPM severo mira el perfil hormonal a lo largo del ciclo — no en un solo punto —, evalúa cómo está durmiendo esa persona, qué está pasando con su estado nutricional, con la inflamación. El objetivo no es aguantar mejor. Es entender por qué tu cuerpo específico responde así, y actuar sobre las causas." },
    ],
  },

  // Ronda 2 ─────────────────────────────────────────────────────────────────
  {
    slug: "dormir-8-horas-no-es-suficiente",
    title: "Duermo mis horas pero sigo agotado: qué está pasando",
    excerpt: "Si duermes 7 u 8 horas y aun así te levantas sin energía, el problema no es la cantidad de sueño. Aquí te explicamos qué puede estar fallando y por qué importa atenderlo.",
    date: "2026-03-23",
    dateFormatted: "23 de marzo de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Sueño",
    tags: ["sueño no reparador", "fatiga", "insomnio", "calidad del sueño"],
    image: u("1531746020-1b38a7c9a1fd"),
    readTime: 7,
    content: [
      { type: "p", text: "\"Pero si duermo bien\" — eso es lo que dices cuando alguien sugiere que quizás el problema es el sueño. Y técnicamente tienes razón: cumples las horas. Siete, a veces ocho. Te acuestas a una hora razonable. No trasnochas. Y aun así, cada mañana es una negociación con la alarma." },
      { type: "p", text: "La cafeína de las 7 a.m. es obligatoria. La de las 11 también. A las 3 de la tarde el cuerpo pide la siesta que no puedes tomarte. Y esa sensación de arrastrar los pies — de funcionar al 70% — se ha convertido en tu estado normal. Tan normal que ya ni la cuestionas." },
      { type: "h2", text: "Horas en cama no es lo mismo que sueño reparador" },
      { type: "p", text: "El sueño tiene fases. Las que importan para despertar con energía — el sueño profundo de onda lenta, donde el cuerpo se repara, y el sueño REM, donde el cerebro procesa — representan solo una parte del tiempo total en cama. Una persona puede estar 8 horas durmiendo y pasar la mayor parte de ese tiempo en sueño superficial, rozando la superficie sin llegar al fondo. El resultado: muchas horas, poco descanso." },
      { type: "h2", text: "Señales de que tu sueño no está reparando" },
      { type: "ul", items: [
        "Te despiertas con la misma sensación de cansancio con la que te dormiste",
        "Necesitas alarma aunque hayas dormido suficiente",
        "Niebla mental en las primeras horas del día que no termina de despejarse",
        "Humor irritable o plano sin razón aparente",
        "Antojos de dulce o carbohidratos durante el día — el cuerpo buscando energía rápida",
        "Te quedas dormido en el sofá sin haberlo planeado",
      ]},
      { type: "h2", text: "Qué puede estar interrumpiendo las fases profundas" },
      { type: "p", text: "Microdespertares que no recuerdas — muy frecuentes en apnea del sueño no diagnosticada. Ansiedad de baja intensidad que mantiene el sistema nervioso levemente activado toda la noche. Déficits nutricionales que afectan la producción de melatonina. Ritmos circadianos desajustados por falta de exposición a la luz natural en las mañanas. Ninguna de estas cosas aparece si le dices al médico 'duermo 8 horas': hay que buscarlas." },
      { type: "quote", text: "Hay personas que llevan años creyendo que son malos durmientes por naturaleza. La mayoría de las veces hay una causa concreta. Y si hay una causa, hay algo que hacer." },
    ],
  },
  {
    slug: "dolor-cronico-y-sueno-circulo-vicioso",
    title: "El dolor que no te deja dormir (y el insomnio que lo empeora)",
    excerpt: "El dolor crónico y el mal sueño se alimentan mutuamente en un ciclo que pocos médicos abordan de frente. Entender la conexión es el primer paso para salir de él.",
    date: "2026-03-16",
    dateFormatted: "16 de marzo de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Dolor Crónico",
    tags: ["dolor crónico", "insomnio", "sueño", "fibromialgia"],
    image: u("1506126613408-eca07ce68773"),
    readTime: 6,
    content: [
      { type: "p", text: "Hay una crueldad particular en esto: el dolor te impide dormir. Y la falta de sueño hace que el dolor del día siguiente sea más intenso. Que lo toleres menos. Que dure más. Y así te quedas atrapado entre dos problemas que se alimentan mutuamente — sin que nadie te haya explicado por qué ocurre ni cómo se interrumpe." },
      { type: "h2", text: "Por qué el sueño cambia cómo percibes el dolor" },
      { type: "p", text: "Durante el sueño profundo, el cuerpo libera hormona de crecimiento y moléculas antiinflamatorias que modulan activamente las señales de dolor. Cuando ese sueño se fragmenta o acorta, el umbral de dolor baja: estímulos que normalmente no dolerían, duelen. Los que ya duelen, duelen más. Esto no es psicológico — es neurofisiología documentada. La privación de sueño activa las mismas vías cerebrales que el daño tisular." },
      { type: "h2", text: "El ciclo que nadie interrumpe" },
      { type: "p", text: "El dolor nocturno fragmenta el sueño. El sueño fragmentado reduce la tolerancia al dolor. La mayor sensibilidad genera ansiedad anticipatoria — miedo a que esta noche también sea mala. Esa ansiedad dificulta conciliar el sueño. El ciclo se repite y cada vuelta lo hace un poco más fuerte." },
      { type: "quote", text: "Tratar solo el dolor sin abordar el sueño — o el sueño sin abordar el dolor — es como intentar vaciar un bote con un agujero. El agujero va primero." },
      { type: "h2", text: "Por qué nadie lo trata junto" },
      { type: "p", text: "Los sistemas de salud están organizados por especialidades: el reumatólogo ve el dolor, el neurólogo ve el sueño. Rara vez alguien los mira juntos como parte del mismo problema. El resultado son tratamientos parciales que funcionan a medias — o medicamentos que alivian uno y empeoran el otro." },
      { type: "h2", text: "Lo que hace la diferencia" },
      { type: "p", text: "Una evaluación que pregunte por el sueño cuando evalúa el dolor, y por el dolor cuando evalúa el sueño. Que entienda cómo interactúan en tu caso específico. Que diseñe un plan que los aborde en paralelo. No es un lujo clínico — es la condición mínima para que mejores de verdad." },
    ],
  },
  {
    slug: "senales-fisicas-de-ansiedad",
    title: "El cuerpo que grita lo que la mente calla: síntomas físicos de ansiedad que ignoramos",
    excerpt: "Las palpitaciones, la tensión en el cuello, el intestino revuelto. Tu cuerpo lleva tiempo enviando señales de ansiedad — y probablemente las has estado atendiendo en el lugar equivocado.",
    date: "2026-03-09",
    dateFormatted: "9 de marzo de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Ansiedad",
    tags: ["ansiedad", "síntomas físicos", "sistema nervioso", "salud"],
    image: u("1559839734-2b71ea197ec2"),
    readTime: 6,
    content: [
      { type: "p", text: "El cardiólogo dice que el corazón está bien. El gastroenterólogo descarta causa orgánica. El neurólogo no encuentra nada. Y tú sigues con las palpitaciones, el nudo en el estómago, la tensión en el cuello que no se va con ningún masaje. El cuerpo insiste en que algo pasa — y tiene razón. Lo que pasa es que nadie está buscando en el lugar correcto." },
      { type: "h2", text: "Por qué la ansiedad vive en el cuerpo" },
      { type: "p", text: "La ansiedad activa el sistema nervioso autónomo — la rama que prepara al cuerpo para una amenaza. El corazón late más rápido, los músculos se tensan, la digestión se detiene, la respiración se vuelve superficial. Todo eso tiene sentido cuando hay un peligro real. El problema es cuando ese estado de activación se sostiene en el tiempo, sin una amenaza concreta, porque entonces esos mismos síntomas se vuelven crónicos — y lo que era una respuesta de emergencia se convierte en el estado basal del cuerpo." },
      { type: "h2", text: "Síntomas físicos de ansiedad que se confunden con otras cosas" },
      { type: "ul", items: [
        "Palpitaciones o sensación de corazón acelerado sin causa cardíaca",
        "Cuello rígido, mandíbula apretada, cefaleas tensionales que vuelven siempre",
        "Intestino irritable, náuseas, sensación de nudo en el estómago",
        "Dificultad para respirar profundo — sensación de que el aire no alcanza",
        "Mareos o inestabilidad que no es vértigo",
        "Hormigueos en manos, pies o cara",
        "Fatiga que no mejora con descanso",
        "Brotes en la piel sin causa dermatológica clara",
      ]},
      { type: "quote", text: "Hay personas que llevan años yendo de especialista en especialista tratando síntomas físicos que son, en realidad, la forma en que su sistema nervioso pide ayuda." },
      { type: "h2", text: "El costo de tratar solo el síntoma" },
      { type: "p", text: "Descartar causas orgánicas es necesario y correcto. El problema es cuando eso es todo lo que se hace. Sin abordar el sistema nervioso que está generando los síntomas, estos migran o vuelven. El intestino mejora y aparecen las cefaleas. Las cefaleas bajan y vuelven las palpitaciones. El cuerpo sigue hablando — solo que en otro idioma." },
      { type: "p", text: "Un abordaje integrativo mira los síntomas físicos como lo que son: manifestaciones de un sistema nervioso desregulado. Eso cambia completamente qué se hace con ellos." },
    ],
  },
  {
    slug: "sintomas-perimenopausia-que-nadie-explica",
    title: "Perimenopausia: los síntomas que nadie te preparó para tener",
    excerpt: "Insomnio inexplicable, ansiedad nueva, niebla mental, ciclos irregulares. Puede que tengas entre 38 y 50 años y nadie te haya dicho que esto tiene nombre — y solución.",
    date: "2026-03-02",
    dateFormatted: "2 de marzo de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Salud Femenina",
    tags: ["perimenopausia", "menopausia", "salud femenina", "hormonas"],
    image: u("1438761681033-6461ffad8d80"),
    readTime: 7,
    content: [
      { type: "p", text: "Tienes 42 años. O 38. O 47. Empezaste a dormir mal de repente, sin razón aparente. Tienes episodios de ansiedad que antes no tenías. Te cuesta recordar palabras en medio de una conversación y eso nunca te había pasado. Tu ciclo cambió. Estás distinta — y no sabes por qué." },
      { type: "p", text: "El médico dice que estás bien. Los exámenes salen normales. Y tú sabes que algo está pasando, pero no tienes nombre para ponerle. Lo más probable es que sí lo tenga: perimenopausia." },
      { type: "h2", text: "Qué es y por qué se diagnostica tan tarde" },
      { type: "p", text: "La perimenopausia es la transición hormonal que antecede a la menopausia — y puede empezar hasta 10 años antes de que el ciclo se detenga. El estrógeno y la progesterona empiezan a fluctuar de forma impredecible, y esas fluctuaciones afectan el sueño, el estado de ánimo, la memoria, el peso, la libido y la respuesta al estrés. El problema es que estos síntomas llegan dispersos, años antes de lo que se esperaría, y con frecuencia se atribuyen a depresión, ansiedad, estrés laboral o simplemente 'la edad'." },
      { type: "h2", text: "Síntomas que pocas veces se conectan con las hormonas" },
      { type: "ul", items: [
        "Insomnio nuevo o sueño muy fragmentado, especialmente en la segunda mitad de la noche",
        "Ansiedad que apareció o empeoró sin motivo claro",
        "Niebla mental: concentración, memoria de palabras, sensación de lentitud cognitiva",
        "Cambios en el ciclo: más corto, más largo, distinto al de siempre",
        "Sofocos leves — pueden pasar desapercibidos o confundirse con calor ambiental",
        "Irritabilidad o bajones emocionales que no tienen explicación en lo que pasó ese día",
        "Sequedad vaginal o molestias durante las relaciones",
        "Dificultad para mantener el peso sin haber cambiado nada",
      ]},
      { type: "quote", text: "La perimenopausia puede empezar a los 38 años. No necesitas que el ciclo se detenga para que tus hormonas estén cambiando — y para que esos cambios afecten profundamente tu calidad de vida." },
      { type: "h2", text: "Por qué los análisis de sangre no la capturan" },
      { type: "p", text: "FSH, estradiol, progesterona — pueden salir 'normales' en plena perimenopausia, porque las hormonas fluctúan tanto que una sola medición no captura el patrón. Por eso el diagnóstico es clínico: se basa en la historia, la edad, los síntomas y los cambios en el tiempo. Una analítica puntual no dice nada si no se lee en contexto." },
      { type: "p", text: "Si te identificas con esto, no lo normalices. Hay mucho que se puede hacer — y la mayoría de las mujeres que reciben atención adecuada notan una diferencia real." },
    ],
  },

  // Ronda 3 ─────────────────────────────────────────────────────────────────
  {
    slug: "que-le-pasa-cuerpo-sin-dormir-bien",
    title: "Lo que le pasa a tu cuerpo cuando llevas meses sin dormir bien",
    excerpt: "El insomnio crónico no es solo cansancio. Afecta tu peso, tu sistema inmune, tu memoria y tu estado de ánimo de formas que quizás no estás relacionando con el sueño.",
    date: "2026-02-23",
    dateFormatted: "23 de febrero de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Sueño",
    tags: ["insomnio crónico", "salud", "fatiga", "sueño"],
    image: u("1486312338219-ce68d2c6f44d"),
    readTime: 8,
    content: [
      { type: "p", text: "Hay un momento en que el mal sueño deja de ser un problema de energía y se convierte en un problema de salud. No hay una fecha exacta ni un aviso previo. Simplemente, en algún punto, los efectos de semanas y meses de sueño fragmentado empiezan a aparecer en lugares que no esperabas: el peso, el humor, el sistema inmune, la memoria." },
      { type: "p", text: "Y lo más confuso es que nadie los conecta con el sueño. Porque ¿quién relaciona que engordó con que lleva meses durmiendo mal? ¿O que se le olvidan más las cosas con que no está llegando al sueño profundo? Nadie. Por eso vale la pena entender qué está pasando." },
      { type: "h2", text: "Lo que el cuerpo hace mientras duermes — y deja de hacer cuando no" },
      { type: "p", text: "El sueño no es tiempo muerto. Es el momento en que el cuerpo hace las cosas que no puede hacer mientras estás despierto: reparar tejidos, consolidar memorias, regular hormonas, limpiar el cerebro literalmente — el sistema glinfático elimina proteínas de desecho asociadas con el deterioro cognitivo durante el sueño profundo. Cuando ese tiempo se recorta o fragmenta de forma crónica, ese mantenimiento no ocurre. Y los efectos se acumulan." },
      { type: "h2", text: "La conexión con el peso que a nadie le explican" },
      { type: "p", text: "El sueño insuficiente eleva la grelina — la hormona del hambre — y reduce la leptina — la de la saciedad. El resultado: más hambre, más antojos específicos de dulce y carbohidratos, mayor dificultad para sentirte satisfecho. Esto no es falta de voluntad. Es biología. Y explica por qué personas que comen bien y hacen ejercicio no logran mantener el peso cuando duermen mal." },
      { type: "h2", text: "El sistema inmune que empieza a fallar" },
      { type: "p", text: "Después de dos o tres semanas de sueño insuficiente o fragmentado, el sistema inmune empieza a mostrar cambios: menor producción de células NK (las que eliminan células infectadas o tumorales), mayor susceptibilidad a infecciones, y un estado inflamatorio de bajo grado que se sostiene en el tiempo. Infecciones más frecuentes, más lentas en irse. Alergias que empeoran. Recuperaciones que tardan más de lo normal." },
      { type: "quote", text: "No existe ningún sistema en el cuerpo que no se vea afectado por el sueño insuficiente sostenido. El sueño no es un lujo — es mantenimiento básico." },
      { type: "h2", text: "Cuándo el cansancio deja de ser normal" },
      { type: "p", text: "Si llevas más de un mes durmiendo mal y empiezas a notar cambios en tu peso, tu humor, tu memoria o tu capacidad de recuperarte de cualquier cosa, esos síntomas están relacionados. Una evaluación médica puede identificar qué está fallando en tu caso específico — y en la mayoría de los casos, hay causas tratables." },
    ],
  },
  {
    slug: "dolor-cronico-y-vida-social",
    title: "Cómo el dolor crónico destruye tu vida social — y qué hacer al respecto",
    excerpt: "Cancelar planes, sentirte incomprendido, alejarte de quien quieres. El dolor crónico tiene un costo social que nadie habla. Aquí lo nombramos — y lo abordamos.",
    date: "2026-02-16",
    dateFormatted: "16 de febrero de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Dolor Crónico",
    tags: ["dolor crónico", "salud mental", "aislamiento", "bienestar"],
    image: u("1506126613408-eca07ce68773"),
    readTime: 6,
    content: [
      { type: "p", text: "Primero cancelas un plan porque ese día el dolor es insoportable. Luego cancelas otro. Y otro. Con el tiempo dejas de comprometerte a nada, porque no sabes cómo estarás. Tus amigos dejan de invitarte — no por maldad, sino porque aprendieron a no esperarte. Y tú terminas solo con tu dolor, que curiosamente se alimenta del aislamiento." },
      { type: "h2", text: "El costo que nadie mide" },
      { type: "p", text: "El dolor crónico tiene síntomas que aparecen en los estudios clínicos y síntomas que no. La pérdida de vida social, el deterioro de las relaciones cercanas, la identidad que se va erosionando — 'yo antes era de los que...' — son consecuencias reales pero que rara vez entran en la consulta. El médico pregunta dónde duele y cuánto. No qué perdiste en el camino." },
      { type: "h2", text: "Lo que sienten las personas con dolor crónico y pocas veces dicen" },
      { type: "ul", items: [
        "Vergüenza o culpa por cancelar una vez más",
        "Sensación de ser una carga para la pareja o la familia",
        "La frase 'pero si no te ves enfermo' como puñalada suave",
        "Duelo real por la vida que tenían antes del dolor",
        "Ansiedad anticipatoria ante actividades que antes disfrutaban",
        "Soledad — incluso rodeados de gente",
      ]},
      { type: "quote", text: "No es que quieras aislarte. Es que el costo energético de salir, explicarte y gestionar las expectativas ajenas a veces supera la energía disponible ese día." },
      { type: "h2", text: "Por qué el aislamiento hace el dolor más intenso" },
      { type: "p", text: "La conexión social tiene efectos analgésicos documentados. La interacción positiva libera oxitocina y endorfinas que modulan la percepción del dolor. El aislamiento, por el contrario, activa respuestas de estrés que lo amplifican. No es casualidad que pacientes con redes sociales activas reporten mejor manejo de su condición — incluso con el mismo diagnóstico y la misma severidad." },
      { type: "h2", text: "Un plan que incluya la dimensión humana" },
      { type: "p", text: "Un buen abordaje del dolor crónico no puede ignorar su impacto en la vida social y en la identidad del paciente. No solo los síntomas físicos — también las estrategias para mantener vínculos, comunicar límites sin culpa, y recuperar gradualmente actividades con significado. El objetivo no es solo reducir el dolor. Es recuperar una vida." },
    ],
  },
  {
    slug: "burnout-cuando-el-cansancio-es-una-condicion",
    title: "Burnout: cuándo el agotamiento pasa de ser cansancio a ser una condición médica",
    excerpt: "No es flojera, no es debilidad y no se soluciona con vacaciones. El burnout es el agotamiento del sistema nervioso — y tiene señales específicas que conviene reconocer a tiempo.",
    date: "2026-02-09",
    dateFormatted: "9 de febrero de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Ansiedad",
    tags: ["burnout", "agotamiento", "estrés crónico", "salud mental"],
    image: u("1516534775068-ba3e7458af70"),
    readTime: 7,
    content: [
      { type: "p", text: "Llegaste a las vacaciones completamente vaciado. Dos semanas después, de vuelta al trabajo, la sensación no cambió. O quizás ya ni puedes tomarte vacaciones — porque el solo pensamiento de lo que te espera al regresar genera más estrés que el trabajo mismo." },
      { type: "p", text: "Eso no es cansancio normal. Eso es burnout. Y la diferencia importa." },
      { type: "h2", text: "Qué es el burnout — y qué no es" },
      { type: "p", text: "La OMS lo reconoce como un fenómeno ocupacional caracterizado por tres cosas: agotamiento energético, distancia mental creciente del trabajo, y reducción de la eficacia profesional. No es depresión, aunque puede precederla. No es estrés, aunque el estrés crónico es su causa principal. Es el resultado de un sistema nervioso que estuvo en modo de alerta demasiado tiempo — y llegó a su límite operativo." },
      { type: "h2", text: "Señales que suelen ignorarse hasta que ya es tarde" },
      { type: "ul", items: [
        "Cansancio que no mejora con descanso, ni siquiera después de un fin de semana largo",
        "Cinismo o distancia emocional ante cosas que antes te importaban",
        "Sensación de que nada de lo que haces tiene impacto real",
        "Dificultad para concentrarte en tareas simples que antes hacías automáticamente",
        "Irritabilidad desproporcionada, especialmente con las personas más cercanas",
        "Infecciones recurrentes, dolores musculares, problemas digestivos sin causa clara",
        "Imposibilidad de desconectarte mentalmente fuera del horario laboral",
      ]},
      { type: "quote", text: "El burnout no llega de golpe. Se construye lentamente, a fuerza de ignorar señales menores, hasta que el cuerpo hace lo que la mente no pudo: parar." },
      { type: "h2", text: "Por qué las vacaciones no lo resuelven" },
      { type: "p", text: "El burnout no es falta de descanso puntual — es la acumulación de un sistema nervioso que nunca bajó del estado de alerta. Una semana de playa puede aliviar la tensión superficial, pero no cambia el patrón de activación crónica. Al regresar, el contexto es el mismo, la fisiología no cambió, y el ciclo continúa. Más rápido que antes, de hecho, porque la reserva ya estaba agotada." },
      { type: "h2", text: "Cuándo pedir ayuda" },
      { type: "p", text: "Si llevas más de un mes así, si está afectando tus relaciones o tu rendimiento de forma sostenida, o si sientes que ya no reconoces quién eras antes de este estado — es el momento. El burnout tiene solución, pero requiere más que descanso: requiere entender qué le está pasando a tu sistema nervioso, cambiar las condiciones que lo produjeron, y darle al cuerpo lo que necesita para recuperar su capacidad de regularse." },
    ],
  },
  {
    slug: "ciclo-menstrual-senales-de-salud",
    title: "Tu ciclo como brújula: señales que tu período te da sobre tu salud",
    excerpt: "El ciclo menstrual es el quinto signo vital para la mujer. Lo que ves cada mes — la regularidad, el color, el dolor — habla de tu salud hormonal, inmune y metabólica en general.",
    date: "2026-02-02",
    dateFormatted: "2 de febrero de 2026",
    author: "Mary Keting",
    authorRole: "Medicina Integrativa",
    category: "Salud Femenina",
    tags: ["ciclo menstrual", "salud femenina", "hormonas", "bienestar"],
    image: u("1571019613454-1cb2f99b2d8b"),
    readTime: 6,
    content: [
      { type: "p", text: "Durante mucho tiempo, el ciclo menstrual se trató en consulta como un detalle administrativo: fecha de última regla, siguiente pregunta. Como si lo que ocurre cada mes fuera solo un marcador de tiempo y no una fuente de información sobre el cuerpo." },
      { type: "p", text: "Hoy lo entendemos diferente. El ciclo menstrual es, para las mujeres en edad reproductiva, uno de los indicadores más sensibles de salud general. Cuando algo cambia — la regularidad, la intensidad, el dolor, el color — hay algo que vale la pena escuchar." },
      { type: "h2", text: "Qué es un ciclo saludable" },
      { type: "p", text: "Entre 21 y 35 días. Entre 3 y 7 días de sangrado. Un volumen moderado — ni tan escaso que apenas mancha ni tan abundante que requiera cambios de protección cada hora o dos. Algo de molestia premenstrual puede ser común; el dolor que requiere analgésicos fuertes o que te impide funcionar no lo es, aunque lo hayas normalizado hace años." },
      { type: "h2", text: "Señales que merecen atención" },
      { type: "ul", items: [
        "Ciclos menores de 21 días: puede indicar fase lútea insuficiente",
        "Ciclos irregulares o muy largos: frecuentemente asociados con SOP",
        "Sangrado muy abundante: fibromas, adenomiosis o alteraciones tiroideas",
        "Ausencia de menstruación sin embarazo: hipotiroidismo, amenorrea hipotalámica, SOP",
        "Dolor intenso o incapacitante: endometriosis o adenomiosis merecen evaluación",
        "Sangrado entre períodos: siempre merece investigarse",
        "Cambio brusco en tu patrón habitual, aunque el nuevo patrón parezca 'normal'",
      ]},
      { type: "quote", text: "Si tu ciclo cambió, tu cuerpo te está diciendo algo. El trabajo médico es escucharlo — no normalizarlo." },
      { type: "h2", text: "El ciclo como espejo del sistema hormonal y metabólico" },
      { type: "p", text: "El ciclo menstrual refleja el equilibrio entre estrógenos, progesterona, hormonas tiroideas, insulina y cortisol. Un ciclo irregular no es un problema aislado: es una señal de que algo en ese equilibrio merece atención. El estrés crónico puede suprimir la ovulación. El hipotiroidismo puede alargar los ciclos. La resistencia a la insulina puede generar irregularidad con ovarios poliquísticos. Cada patrón tiene una historia detrás." },
      { type: "p", text: "Registrar tu ciclo durante dos o tres meses — duración, intensidad, síntomas, estado de ánimo — es la herramienta más simple y poderosa para entender tu salud hormonal. Esa información, en manos de un médico que sepa leerla, puede orientar una evaluación mucho más precisa que cualquier analítica hecha sin contexto." },
    ],
  },
]

export function getAllSlugs(): string[] {
  return posts.map((p) => p.slug)
}

export function getPost(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug)
}
