export type ContentBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "quote"; text: string }

export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  date: string
  dateFormatted: string
  author: string
  authorRole: string
  category: string
  tags: string[]
  image: string
  readTime: number
  content: ContentBlock[]
}

const u = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&h=630&q=85`

export const posts: BlogPost[] = [
  // Ronda 1 ─────────────────────────────────────────────────────────────────
  {
    slug: "por-que-me-despierto-a-las-3am",
    title: "Las 3 de la madrugada: por qué tu cerebro te despierta (y cómo volver a dormir)",
    excerpt: "Despertar en mitad de la noche y no poder volver a dormirte es más común de lo que crees. Aquí explicamos qué está pasando en tu cuerpo — y qué puedes hacer.",
    date: "2025-01-08",
    dateFormatted: "8 de enero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Sueño",
    tags: ["insomnio", "sueño fragmentado", "despertar nocturno", "ritmo circadiano"],
    image: u("1541480601022-2308c0f02487"),
    readTime: 6,
    content: [
      { type: "p", text: "Son las 3:17 de la madrugada. Te despertaste sin saber por qué, la mente ya está activa y sabes que las próximas dos horas serán una batalla. Si esto te suena familiar, no estás solo: el despertar en mitad de la noche es una de las quejas de sueño más frecuentes en consulta — y una de las menos entendidas." },
      { type: "h2", text: "No es que 'no puedas dormir': tu cerebro está haciendo algo concreto" },
      { type: "p", text: "El sueño no es un estado uniforme. Pasamos por ciclos de 90 minutos que alternan entre sueño profundo (reparador) y sueño REM (de sueños). El despertar alrededor de las 3 a.m. suele coincidir con el final de un ciclo REM y el inicio de un período donde el sueño es naturalmente más ligero. Lo que te mantiene despierto no es el despertar en sí — es lo que ocurre después: el cortisol matutino empieza a subir, la mente se activa, y el cuerpo interpreta que ya es hora de levantarse." },
      { type: "h2", text: "Factores que hacen que el despertar se prolongue" },
      { type: "ul", items: [
        "Estrés crónico o ansiedad sostenida: el sistema nervioso queda en alerta incluso dormido",
        "Azúcar en sangre inestable: una caída nocturna de glucosa puede disparar adrenalina",
        "Temperatura corporal elevada: habitaciones cálidas interrumpen el sueño profundo",
        "Alcohol en la noche: fragmenta los ciclos y suprime el sueño REM",
        "Dolor crónico no tratado: el umbral de dolor baja por la noche",
      ]},
      { type: "quote", text: "El problema no siempre es quedarte dormido — a veces es quedarte dormido después de despertar. Y eso tiene causas muy específicas que se pueden abordar." },
      { type: "h2", text: "Lo que no ayuda (aunque parezca lógico)" },
      { type: "p", text: "Mirar el celular, revisar la hora cada 10 minutos, o levantarte a comer algo refuerzan la asociación entre 'las 3 a.m.' y 'actividad', haciendo el problema crónico. El cerebro aprende patrones con mucha facilidad — y los deshace con más dificultad." },
      { type: "h2", text: "Cuándo buscar ayuda médica" },
      { type: "p", text: "Si llevas más de tres semanas despertando con frecuencia, si el cansancio diurno afecta tu trabajo o tu humor, o si sientes que el sueño simplemente no es reparador aunque duermas horas suficientes, vale la pena una evaluación. El sueño fragmentado crónico tiene consecuencias reales en inflamación, metabolismo y salud mental — y tiene solución." },
    ],
  },
  {
    slug: "cuando-el-dolor-no-tiene-explicacion",
    title: "Cuando el dolor no tiene explicación: qué hacer si tus exámenes salen normales",
    excerpt: "Tener dolor real con exámenes normales no significa que estés inventándotelo. Significa que el sistema médico convencional aún no encontró la causa — y eso tiene solución.",
    date: "2025-01-12",
    dateFormatted: "12 de enero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Dolor Crónico",
    tags: ["dolor crónico", "fibromialgia", "diagnóstico", "medicina integrativa"],
    image: u("1571019613454-1cb2f99b2d8b"),
    readTime: 7,
    content: [
      { type: "p", text: "\"Sus exámenes están normales\". Para alguien que lleva meses con dolor, esa frase puede ser una de las más frustrantes que existe. No porque los médicos estén equivocados — los exámenes pueden efectivamente estar normales — sino porque la conclusión implícita suele ser: 'entonces el problema está en tu cabeza'. Y eso no es cierto." },
      { type: "h2", text: "Por qué los exámenes convencionales no capturan todo el dolor" },
      { type: "p", text: "La medicina convencional está muy bien equipada para detectar daño estructural: fracturas, tumores, inflamación aguda. Pero el dolor crónico frecuentemente ocurre en ausencia de daño estructural visible. La fibromialgia, el síndrome de sensibilización central, el dolor neuropático y el dolor miofascial son condiciones reales, respaldadas por décadas de investigación, que no aparecen en una radiografía ni en un análisis de sangre estándar." },
      { type: "h2", text: "Señales de que podrías estar ante un dolor crónico no diagnosticado" },
      { type: "ul", items: [
        "Dolor difuso que se mueve o cambia de lugar",
        "Fatiga persistente que no mejora con descanso",
        "Hipersensibilidad a estímulos: la ropa roza, la luz molesta, los ruidos irritan más de lo habitual",
        "Múltiples síntomas 'sin relación': intestino irritable, cefaleas, problemas de sueño",
        "Síntomas que empeoran con el estrés o la falta de sueño",
        "Varios médicos sin un diagnóstico claro después de meses de consultas",
      ]},
      { type: "quote", text: "El dolor es siempre real. Si lo sientes, existe. El trabajo médico es encontrar su origen — no descartarlo porque no aparezca en los exámenes de rutina." },
      { type: "h2", text: "Un enfoque diferente: buscar el sistema, no solo el síntoma" },
      { type: "p", text: "La medicina integrativa aborda el dolor crónico mirando el cuadro completo: el sistema nervioso, el sistema inmune, el microbioma, los patrones de sueño, el estado nutricional y los factores de estrés. A menudo, el dolor sin explicación tiene múltiples causas que se potencian entre sí — y cuando se abordan en conjunto, los pacientes encuentran alivio que nunca tuvieron con tratamientos parciales." },
      { type: "h2", text: "El siguiente paso" },
      { type: "p", text: "Si llevas tiempo con dolor que nadie ha sabido explicar, no te resignes. Busca una segunda opinión con un enfoque integrativo. El diagnóstico diferencial en dolor crónico requiere tiempo y una historia clínica detallada — no solo los exámenes de siempre." },
    ],
  },
  {
    slug: "ansiedad-vs-estres-como-diferenciarlos",
    title: "Ansiedad o estrés: cómo diferenciarlos y por qué importa la distinción",
    excerpt: "\"Son los nervios\" o \"es el trabajo\" — la ansiedad se disfraza de estrés cotidiano durante años. Entender la diferencia puede cambiar completamente cómo la abordas.",
    date: "2025-01-17",
    dateFormatted: "17 de enero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Ansiedad",
    tags: ["ansiedad", "estrés", "salud mental", "bienestar emocional"],
    image: u("1507003211169-0a1dd7228f2d"),
    readTime: 5,
    content: [
      { type: "p", text: "\"Estoy muy estresado\" es la frase que más se escucha en consulta cuando el paciente lleva meses con palpitaciones, tensión muscular, insomnio y una sensación permanente de que algo malo está por pasar. El estrés es la explicación que usamos para todo lo que nos perturba. El problema es que a veces eso que llamamos estrés tiene otro nombre — y otro tratamiento." },
      { type: "h2", text: "La diferencia clave: causa externa vs. activación interna" },
      { type: "p", text: "El estrés tiene un desencadenante identificable: la reunión de mañana, la deuda pendiente, el conflicto familiar. Cuando el factor externo desaparece o se resuelve, el estrés baja. La ansiedad, en cambio, persiste incluso cuando no hay un factor concreto que la justifique — o salta de una preocupación a otra sin que ninguna se resuelva del todo. El cerebro ansioso no necesita una razón real para activarse: crea las suyas." },
      { type: "h2", text: "Señales de que puede ser ansiedad y no solo estrés" },
      { type: "ul", items: [
        "Preocupación excesiva sobre cosas que 'racionalmente' sabes que no son graves",
        "Tensión muscular crónica, especialmente en cuello, mandíbula y hombros",
        "Dificultad para dejar de pensar antes de dormir",
        "Sensación de urgencia o apuro constante sin motivo claro",
        "Irritabilidad que no corresponde a los eventos del día",
        "Síntomas físicos recurrentes sin causa médica (palpitaciones, mareos, dificultad para respirar)",
        "Evitación de situaciones o compromisos por anticipar que algo saldrá mal",
      ]},
      { type: "quote", text: "La ansiedad no te avisa que llegó. Se instala gradualmente, disfrazada de 'personalidad ansiosa' o 'soy muy exigente conmigo mismo', hasta que afecta la calidad de vida de forma clara." },
      { type: "h2", text: "Por qué importa diferenciarlos" },
      { type: "p", text: "Si lo que tienes es estrés situacional, las estrategias de manejo del tiempo, los límites laborales y el descanso activo suelen ser suficientes. Si lo que tienes es ansiedad — un patrón de activación sostenido del sistema nervioso — esas mismas estrategias ayudan poco sin abordar la fisiología subyacente. El tratamiento es diferente porque el mecanismo es diferente." },
      { type: "h2", text: "El primer paso es nombrarlo bien" },
      { type: "p", text: "No para etiquetarte, sino para dejar de buscar el \"motivo\" que justifique cómo te sientes. La ansiedad no siempre tiene un porqué obvio — y eso es parte de su naturaleza. Una evaluación médica puede ayudarte a entender qué está ocurriendo en tu sistema nervioso y qué opciones tienes para manejarlo, más allá de \"intenta relajarte\"." },
    ],
  },
  {
    slug: "spm-severo-no-es-normal",
    title: "SPM severo: cuando tu ciclo te tumba y te dicen que \"es normal\"",
    excerpt: "No es dramatismo ni falta de carácter. El síndrome premenstrual severo es una condición médica real — y decirte que \"todas las mujeres lo tienen\" no es una respuesta suficiente.",
    date: "2025-01-22",
    dateFormatted: "22 de enero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Salud Femenina",
    tags: ["SPM", "síndrome premenstrual", "salud femenina", "ciclo menstrual"],
    image: u("1554151228-14d9def656e4"),
    readTime: 6,
    content: [
      { type: "p", text: "Cada mes, entre 5 y 10 días antes de la menstruación, algo cambia. El estado de ánimo cae en picada, el cuerpo duele, la hinchazón es real, y la irritabilidad o la tristeza son tan intensas que afectan el trabajo, las relaciones y tu capacidad de funcionar. Y cuando lo mencionas, la respuesta es: \"es normal, somos así\"." },
      { type: "h2", text: "La diferencia entre SPM y TDPM" },
      { type: "p", text: "El síndrome premenstrual (SPM) afecta a entre el 30% y el 40% de mujeres en edad reproductiva con síntomas leves a moderados. Pero existe una forma severa llamada Trastorno Disfórico Premenstrual (TDPM) que afecta al 3–8% y que va mucho más allá de 'estar sensible': incluye episodios de disforia intensa, llanto sin motivo aparente, irritabilidad que puede arruinar relaciones, y en algunos casos, pensamientos que asustan. No es SPM moderado — es una condición que requiere atención específica." },
      { type: "h2", text: "Síntomas que indican que tu SPM merece atención médica" },
      { type: "ul", items: [
        "Los síntomas aparecen de forma predecible en la segunda mitad del ciclo y desaparecen con la menstruación",
        "Afectan tu trabajo, tus relaciones o tu capacidad de hacer actividades cotidianas",
        "La irritabilidad o tristeza son desproporcionadas y tú misma las percibes como 'no soy yo'",
        "Hay síntomas físicos intensos: sensibilidad en los senos, hinchazón, cefaleas, fatiga",
        "Has llegado a pensar que 'antes del período eres otra persona'",
      ]},
      { type: "quote", text: "El SPM severo no es carácter. No es exageración. Es una respuesta hormonal desproporcionada con mecanismos neurobiológicos identificables — y se puede abordar." },
      { type: "h2", text: "Por qué se subdiagnostica y se minimiza" },
      { type: "p", text: "Durante décadas, el malestar premenstrual fue culturalmente normalizado y médicamente ignorado. Muchas mujeres aprenden desde jóvenes que el dolor y la disfunción cíclica 'son parte del ser mujer' — y dejan de reportarlos. El resultado es que llegan a consulta años después, habiendo adaptado su vida entera alrededor de esos días, cuando podrían haber recibido ayuda mucho antes." },
      { type: "h2", text: "El abordaje que funciona" },
      { type: "p", text: "Una evaluación integrativa del SPM severo incluye el análisis del perfil hormonal a lo largo del ciclo, los patrones de sueño (que se ven profundamente afectados), el estado nutricional y la respuesta inflamatoria. El objetivo es entender por qué tu ciclo produce esa respuesta en tu cuerpo específico — y diseñar un plan que reduzca su impacto de forma real y sostenida." },
    ],
  },

  // Ronda 2 ─────────────────────────────────────────────────────────────────
  {
    slug: "dormir-8-horas-no-es-suficiente",
    title: "Duermo mis horas pero sigo agotado: qué está pasando",
    excerpt: "Si duermes 7 u 8 horas y aun así te levantas sin energía, el problema no es la cantidad de sueño. Aquí te explicamos qué puede estar fallando y por qué importa atenderlo.",
    date: "2025-01-27",
    dateFormatted: "27 de enero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Sueño",
    tags: ["sueño no reparador", "fatiga", "insomnio", "calidad del sueño"],
    image: u("1531746020-1b38a7c9a1fd"),
    readTime: 7,
    content: [
      { type: "p", text: "\"Duermo bien\" — o eso crees. Cumples las 7 u 8 horas que todo el mundo recomienda. Pero te levantas arrastrándote, necesitas cafeína para funcionar, y a las 3 de la tarde ya quisieras volver a la cama. La sensación es desconcertante: si estás durmiendo suficiente, ¿por qué tu cuerpo actúa como si no hubieras dormido nada?" },
      { type: "h2", text: "La cantidad de sueño no es lo mismo que la calidad del sueño" },
      { type: "p", text: "Las horas de sueño son solo una parte de la ecuación. Lo que realmente restaura el cuerpo y la mente es la arquitectura del sueño: cuánto tiempo pasas en sueño profundo (fase 3, donde se repara el tejido y consolida la memoria) y en sueño REM (donde el cerebro procesa emociones e información). Una persona puede estar 8 horas en cama pero pasar la mayor parte en sueño superficial, sin llegar a las fases reparadoras." },
      { type: "h2", text: "Señales de que tu sueño no es reparador" },
      { type: "ul", items: [
        "Te despiertas con la misma sensación de cansancio con la que te dormiste",
        "Necesitas alarma y todavía te cuesta levantarte",
        "Sientes niebla mental en las primeras horas del día",
        "Tu humor es irritable o plano sin razón aparente",
        "Tienes antojos de azúcar o carbohidratos durante el día",
        "Te quedas dormido involuntariamente en el sofá o en reuniones",
      ]},
      { type: "h2", text: "Qué puede estar afectando la calidad de tu sueño" },
      { type: "p", text: "Las causas más frecuentes de sueño no reparador incluyen microdespertares que no recuerdas (comunes en apnea del sueño no diagnosticada), ansiedad de baja intensidad que mantiene el sistema nervioso activado, déficits nutricionales que afectan la producción de melatonina y serotonina, y ritmos circadianos desajustados por exposición irregular a la luz natural." },
      { type: "quote", text: "Muchos pacientes llevan años creyendo que son 'malos durmientes' por naturaleza. La mayoría de las veces hay una causa concreta — y se puede abordar." },
      { type: "h2", text: "Por qué vale la pena investigarlo" },
      { type: "p", text: "El sueño no reparador crónico no es solo cansancio: está asociado con mayor riesgo de síndrome metabólico, depresión, deterioro cognitivo prematuro e inflamación sistémica. Si llevas meses en este ciclo, una evaluación médica integrativa puede identificar qué está fallando en tu caso específico — no en el promedio estadístico." },
    ],
  },
  {
    slug: "dolor-cronico-y-sueno-circulo-vicioso",
    title: "El dolor que no te deja dormir (y el insomnio que lo empeora)",
    excerpt: "El dolor crónico y el mal sueño se alimentan mutuamente en un ciclo que pocos médicos abordan de frente. Entender la conexión es el primer paso para salir de él.",
    date: "2025-02-01",
    dateFormatted: "1 de febrero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Dolor Crónico",
    tags: ["dolor crónico", "insomnio", "sueño", "fibromialgia"],
    image: u("1506126613408-eca07ce68773"),
    readTime: 6,
    content: [
      { type: "p", text: "Hay una crueldad particular en la combinación de dolor crónico e insomnio: el dolor te impide dormir, y la falta de sueño hace que el dolor sea más intenso al día siguiente. Es un círculo que se retroalimenta sin que nadie te haya explicado por qué ocurre ni cómo interrumpirlo." },
      { type: "h2", text: "Por qué el sueño y el dolor están tan conectados" },
      { type: "p", text: "Durante el sueño profundo, el cuerpo libera hormona de crecimiento y citoquinas antiinflamatorias que modulan la percepción del dolor. Cuando ese sueño se interrumpe o es insuficiente, el umbral de dolor baja: los estímulos que normalmente no dolerían, duelen. Los que ya duelen, duelen más. Esto no es psicológico — es neurofisiología documentada. La privación de sueño activa las mismas vías cerebrales que el daño tisular." },
      { type: "h2", text: "El ciclo que nadie interrumpe" },
      { type: "ul", items: [
        "El dolor nocturno fragmenta el sueño",
        "El sueño fragmentado reduce la tolerancia al dolor",
        "La mayor sensibilidad al dolor genera más ansiedad anticipatoria",
        "La ansiedad dificulta aún más conciliar el sueño",
        "El ciclo se repite y se intensifica con el tiempo",
      ]},
      { type: "quote", text: "Tratar solo el dolor sin abordar el sueño, o viceversa, es como intentar vaciar un bote con un agujero. Hay que cerrar el agujero primero." },
      { type: "h2", text: "Por qué la medicina convencional suele tratar solo uno de los dos" },
      { type: "p", text: "Los sistemas de salud están organizados por especialidades: un reumatólogo ve el dolor, un neurólogo ve el sueño. Rara vez alguien mira los dos juntos como parte del mismo problema. El resultado es que los pacientes reciben tratamientos parciales que funcionan a medias y con frecuencia generan dependencia de medicamentos que no resuelven la raíz." },
      { type: "h2", text: "Qué buscar en una evaluación integral" },
      { type: "p", text: "Un abordaje completo debería evaluar la calidad del sueño como parte del manejo del dolor — y el nivel de dolor como parte de la evaluación del sueño. Preguntar por ambos en la misma consulta, entender cómo interactúan en tu caso específico, y diseñar un plan que los aborde en paralelo es lo que marca la diferencia entre el manejo parcial y la mejora real." },
    ],
  },
  {
    slug: "senales-fisicas-de-ansiedad",
    title: "El cuerpo que grita lo que la mente calla: síntomas físicos de ansiedad que ignoramos",
    excerpt: "Las palpitaciones, la tensión en el cuello, el intestino revuelto. Tu cuerpo lleva tiempo enviando señales de ansiedad — y probablemente las has estado atendiendo en el lugar equivocado.",
    date: "2025-02-06",
    dateFormatted: "6 de febrero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Ansiedad",
    tags: ["ansiedad", "síntomas físicos", "sistema nervioso", "salud"],
    image: u("1559839734-2b71ea197ec2"),
    readTime: 6,
    content: [
      { type: "p", text: "El cardiólogo dice que el corazón está bien. El gastroenterólogo descarta causa orgánica. El neurólogo no encuentra nada. Y sin embargo: palpitaciones, náuseas, tensión en el pecho, hormigueos, mareos. El cuerpo insiste en que algo pasa — y tiene razón. Lo que pasa, a veces, es ansiedad." },
      { type: "h2", text: "Por qué la ansiedad se manifiesta en el cuerpo" },
      { type: "p", text: "La ansiedad activa el sistema nervioso autónomo — específicamente la rama simpática, responsable de la respuesta de 'lucha o huida'. Eso significa que el cuerpo se prepara para una amenaza: el corazón late más rápido, los músculos se tensan, la digestión se detiene, la respiración se vuelve superficial. Cuando ese estado se sostiene en el tiempo (como ocurre en la ansiedad crónica), esos mismos síntomas se vuelven permanentes o recurrentes." },
      { type: "h2", text: "Síntomas físicos frecuentes de ansiedad que se confunden con otras condiciones" },
      { type: "ul", items: [
        "Palpitaciones o taquicardia sin causa cardíaca",
        "Tensión muscular crónica: cuello rígido, mandíbula apretada, cefaleas tensionales",
        "Problemas digestivos: síndrome de intestino irritable, náuseas, sensación de nudo en el estómago",
        "Dificultad para respirar profundo, sensación de falta de aire",
        "Mareos o sensación de inestabilidad sin vértigo real",
        "Hormigueos o entumecimiento en manos, pies o cara",
        "Piel con brotes o picazón sin causa dermatológica identificable",
        "Fatiga intensa que no mejora con descanso",
      ]},
      { type: "quote", text: "Muchos pacientes llevan años yendo de especialista en especialista tratando síntomas físicos que son, en realidad, la forma en que su sistema nervioso pide ayuda." },
      { type: "h2", text: "El costo de tratar el síntoma sin la causa" },
      { type: "p", text: "No hay nada de malo en descartar causas orgánicas — es parte del proceso. El problema es cuando el proceso termina ahí: 'todo está normal, tome este medicamento para el síntoma'. Sin abordar el sistema nervioso subyacente, los síntomas migran o reaparecen. El intestino mejora y aparecen cefaleas. Las cefaleas bajan y vuelven las palpitaciones." },
      { type: "h2", text: "Qué incluye un abordaje integral" },
      { type: "p", text: "Un enfoque integrativo de la ansiedad incluye la evaluación de los síntomas físicos en contexto: no como problemas independientes, sino como manifestaciones del mismo sistema nervioso desregulado. Eso permite un plan que aborda tanto los síntomas como el origen — y que da al paciente herramientas reales para reconocer, entender y regular su propio sistema nervioso." },
    ],
  },
  {
    slug: "sintomas-perimenopausia-que-nadie-explica",
    title: "Perimenopausia: los síntomas que nadie te preparó para tener",
    excerpt: "Insomnio inexplicable, ansiedad nueva, niebla mental, ciclos irregulares. Puede que tengas entre 38 y 50 años y nadie te haya dicho que esto tiene nombre — y solución.",
    date: "2025-02-11",
    dateFormatted: "11 de febrero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Salud Femenina",
    tags: ["perimenopausia", "menopausia", "salud femenina", "hormonas"],
    image: u("1438761681033-6461ffad8d80"),
    readTime: 7,
    content: [
      { type: "p", text: "Empiezas a dormir mal, sin razón aparente. Tienes episodios de ansiedad que antes no tenías. Te cuesta concentrarte en conversaciones o recordar cosas simples. Tu ciclo ya no es tan predecible. Tienes 42 años y el médico te dice que estás \"bien\". Lo que nadie te dijo es que probablemente estás en perimenopausia — la transición hormonal que puede durar hasta 10 años antes de la menopausia y que es, sistemáticamente, subdiagnosticada." },
      { type: "h2", text: "Qué es la perimenopausia y por qué se confunde con otras cosas" },
      { type: "p", text: "La perimenopausia es el período de transición hormonal que antecede a la menopausia. Los niveles de estrógeno y progesterona empiezan a fluctuar de forma impredecible — y esas fluctuaciones afectan literalmente todos los sistemas del cuerpo: el sueño, el estado de ánimo, la memoria, la piel, el peso, la libido y la respuesta al estrés. El problema es que estos síntomas se presentan de forma dispersa, años antes de que el ciclo se detenga, y con frecuencia se atribuyen a depresión, estrés laboral o simplemente a 'la edad'." },
      { type: "h2", text: "Síntomas perimenopáusicos que frecuentemente no se asocian a hormonas" },
      { type: "ul", items: [
        "Insomnio o sueño muy fragmentado, especialmente en la segunda mitad de la noche",
        "Ansiedad de aparición relativamente nueva o que empeoró sin motivo claro",
        "Niebla mental: dificultad para concentrarse, encontrar palabras, recordar",
        "Cambios en el ciclo: más corto, más largo, con sangrado diferente al habitual",
        "Sensación de calor o sudoración nocturna (sofocos) que pueden ser leves y pasar desapercibidos",
        "Irritabilidad intensa o bajones emocionales cíclicos",
        "Sequedad vaginal o molestias durante las relaciones",
        "Dificultad para recuperar el peso habitual a pesar de no haber cambiado hábitos",
      ]},
      { type: "quote", text: "La perimenopausia puede empezar a los 38 años. No necesitas que tu ciclo se detenga para que tus hormonas estén cambiando — y para que esos cambios afecten tu calidad de vida." },
      { type: "h2", text: "El diagnóstico que nadie te ofrece" },
      { type: "p", text: "Una analítica hormonal estándar (FSH, estradiol, progesterona) puede dar valores 'normales' incluso en plena perimenopausia, porque las hormonas fluctúan tanto que una sola medición no captura el patrón. Por eso el diagnóstico es clínico: se basa en la historia de síntomas, la edad y los patrones de cambio — no solo en un análisis de sangre." },
      { type: "h2", text: "Qué hacer si te identificas con esto" },
      { type: "p", text: "Lo primero es no normalizar síntomas que afectan tu calidad de vida. Lo segundo es buscar un médico que conozca la perimenopausia y que haga una evaluación integrativa: no solo hormonal, sino del sueño, el estado nutricional, la salud metabólica y el bienestar emocional. Hay mucho que se puede hacer — y la mayoría de las mujeres que reciben atención adecuada notan una diferencia significativa." },
    ],
  },

  // Ronda 3 ─────────────────────────────────────────────────────────────────
  {
    slug: "que-le-pasa-cuerpo-sin-dormir-bien",
    title: "Lo que le pasa a tu cuerpo cuando llevas meses sin dormir bien",
    excerpt: "El insomnio crónico no es solo cansancio. Afecta tu peso, tu sistema inmune, tu memoria y tu estado de ánimo de formas que quizás no estás relacionando con el sueño.",
    date: "2025-02-17",
    dateFormatted: "17 de febrero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Sueño",
    tags: ["insomnio crónico", "salud", "fatiga", "sueño"],
    image: u("1486312338219-ce68d2c6f44d"),
    readTime: 8,
    content: [
      { type: "p", text: "Cuando el mal sueño se extiende semanas o meses, deja de ser un problema de energía y se convierte en un problema de salud. El cuerpo usa el sueño para hacer cosas que no puede hacer cuando estás despierto: reparar tejidos, consolidar memorias, regular hormonas, limpiar el cerebro de residuos metabólicos. Cuando ese tiempo se recorta o fragmenta de forma crónica, los efectos se acumulan de formas que sorprenden a muchos pacientes." },
      { type: "h2", text: "Lo que ocurre semana a semana" },
      { type: "ul", items: [
        "Semanas 1–2: irritabilidad, dificultad de concentración, mayor sensibilidad al dolor",
        "Semanas 3–4: el sistema inmune empieza a deteriorarse, mayor susceptibilidad a infecciones",
        "Mes 2–3: cambios en el metabolismo de glucosa, aumento del apetito (especialmente por dulces y carbohidratos)",
        "Más de 3 meses: mayor riesgo de ansiedad y depresión, deterioro de la memoria de trabajo",
      ]},
      { type: "h2", text: "La conexión con el peso que nadie te cuenta" },
      { type: "p", text: "El sueño insuficiente eleva la grelina (hormona del hambre) y reduce la leptina (hormona de saciedad). Esto explica por qué quienes duermen mal tienen más antojos y mayor dificultad para mantener o bajar de peso — aunque coman bien y hagan ejercicio. Es biología, no falta de voluntad." },
      { type: "h2", text: "El cerebro bajo privación de sueño" },
      { type: "p", text: "Durante el sueño profundo, el sistema glinfático del cerebro literalmente se lava a sí mismo, eliminando proteínas de desecho asociadas con el deterioro cognitivo. Dormir mal de forma crónica ralentiza este proceso. A corto plazo se siente como niebla mental y olvidos frecuentes; a largo plazo, la investigación lo asocia con mayor riesgo de deterioro cognitivo en la vejez." },
      { type: "quote", text: "No existe ningún órgano ni sistema en el cuerpo que no se vea afectado negativamente por el sueño insuficiente. El sueño no es un lujo — es mantenimiento básico." },
      { type: "h2", text: "Cuándo el cansancio deja de ser normal" },
      { type: "p", text: "Si llevas más de un mes durmiendo mal y empiezas a notar cambios en tu humor, tu peso, tu memoria o tu tolerancia al estrés, esos síntomas están relacionados. Una evaluación médica puede identificar si hay causas tratables — y en la mayoría de los casos, las hay." },
    ],
  },
  {
    slug: "dolor-cronico-y-vida-social",
    title: "Cómo el dolor crónico destruye tu vida social — y qué hacer al respecto",
    excerpt: "Cancelar planes, sentirte incomprendido, alejarte de quien quieres. El dolor crónico tiene un costo social que nadie habla. Aquí lo nombramos — y lo abordamos.",
    date: "2025-02-22",
    dateFormatted: "22 de febrero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Dolor Crónico",
    tags: ["dolor crónico", "salud mental", "aislamiento", "bienestar"],
    image: u("1438761681033-6461ffad8d80"),
    readTime: 6,
    content: [
      { type: "p", text: "Empiezas cancelando un plan porque ese día el dolor es insoportable. Luego cancelas otro. Y otro. Con el tiempo, dejas de comprometerte a nada porque no sabes cómo estarás. Tus amigos dejan de invitarte — no por maldad, sino porque aprendieron a no esperarte. Y tú terminas solo con tu dolor, que se alimenta del aislamiento." },
      { type: "h2", text: "El costo invisible del dolor crónico" },
      { type: "p", text: "El dolor crónico tiene síntomas que aparecen en los estudios clínicos y síntomas que no. La pérdida de vida social, el deterioro de las relaciones cercanas, la identidad que se va erosionando ('yo antes era de los que...') son consecuencias reales pero que rara vez se abordan en consulta. El médico pregunta dónde duele y cuánto — no qué perdiste en el camino." },
      { type: "h2", text: "Lo que sienten quienes viven con dolor crónico" },
      { type: "ul", items: [
        "Vergüenza o culpa por cancelar compromisos repetidamente",
        "Sensación de ser una carga para familia o pareja",
        "Incomprensión: 'pero si no te ves enfermo...'",
        "Duelo por la vida que tenían antes del dolor",
        "Ansiedad anticipatoria ante actividades que antes disfrutaban",
        "Soledad — incluso rodeados de gente",
      ]},
      { type: "quote", text: "No es que quieras aislarte. Es que el costo energético de salir, explicarte y gestionar las expectativas ajenas a veces supera la energía disponible." },
      { type: "h2", text: "Por qué el aislamiento empeora el dolor" },
      { type: "p", text: "La conexión social tiene efectos analgésicos documentados: la interacción positiva libera oxitocina y endorfinas que modulan la percepción del dolor. El aislamiento, por el contrario, activa respuestas de estrés que amplifican las señales de dolor. No es casualidad que los pacientes con redes sociales activas reporten mejor manejo de su condición — incluso con la misma severidad de diagnóstico." },
      { type: "h2", text: "Un abordaje que incluya la dimensión social" },
      { type: "p", text: "Un buen plan de manejo del dolor crónico no puede ignorar su impacto en la vida social y en la identidad del paciente. Eso implica trabajar tanto los síntomas físicos como las estrategias para mantener vínculos, comunicar límites sin culpa y recuperar gradualmente la participación en actividades significativas. El objetivo no es solo reducir el dolor — es recuperar una vida." },
    ],
  },
  {
    slug: "burnout-cuando-el-cansancio-es-una-condicion",
    title: "Burnout: cuándo el agotamiento pasa de ser cansancio a ser una condición médica",
    excerpt: "No es flojera, no es debilidad y no se soluciona con vacaciones. El burnout es el agotamiento del sistema nervioso — y tiene señales específicas que conviene reconocer a tiempo.",
    date: "2025-02-27",
    dateFormatted: "27 de febrero de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Ansiedad",
    tags: ["burnout", "agotamiento", "estrés crónico", "salud mental"],
    image: u("1516534775068-ba3e7458af70"),
    readTime: 7,
    content: [
      { type: "p", text: "Llegaste a las vacaciones completamente vaciado. Dos semanas después, de vuelta al trabajo, la sensación no cambió. O quizás ya no puedes tomarte vacaciones porque el solo pensamiento de lo que te espera al regresar te genera más estrés que descanso. Eso no es cansancio normal — eso es burnout." },
      { type: "h2", text: "Qué es exactamente el burnout (y qué no es)" },
      { type: "p", text: "La Organización Mundial de la Salud reconoce el burnout como un fenómeno ocupacional caracterizado por agotamiento energético, distancia mental del trabajo, y reducción de la eficacia profesional. No es depresión, aunque puede precederla. No es estrés, aunque el estrés crónico es su causa principal. Es el resultado de un sistema nervioso que estuvo en modo de alerta demasiado tiempo — y llegó a su límite." },
      { type: "h2", text: "Señales de alerta que suelen ignorarse" },
      { type: "ul", items: [
        "Cansancio que no mejora con descanso, incluso después de un fin de semana largo",
        "Cinismo o distancia emocional ante cosas que antes te importaban",
        "Sensación de que nada de lo que haces tiene impacto o sentido",
        "Dificultad para concentrarte en tareas simples",
        "Irritabilidad desproporcionada, especialmente con personas cercanas",
        "Somatizaciones frecuentes: infecciones recurrentes, dolores musculares, problemas digestivos",
        "Dificultad para desconectarte fuera del horario laboral",
      ]},
      { type: "quote", text: "El burnout no llega de golpe. Se construye lentamente, a fuerza de ignorar señales menores hasta que el cuerpo hace lo que la mente no pudo: parar." },
      { type: "h2", text: "Por qué las vacaciones no son suficientes" },
      { type: "p", text: "El burnout no es falta de descanso puntual — es la acumulación de un sistema nervioso que nunca bajó del estado de alerta. Una semana de playa puede aliviar la tensión superficial, pero no resuelve el patrón de activación crónica que instaló el problema. Al regresar, el contexto es el mismo, la fisiología no cambió, y el ciclo continúa." },
      { type: "h2", text: "Cuándo buscar ayuda" },
      { type: "p", text: "Si los síntomas llevan más de un mes, si están afectando tus relaciones o tu rendimiento de forma sostenida, o si sientes que ya no reconoces quién eras antes de este estado, es el momento de pedir una evaluación. El burnout tiene solución — pero requiere un abordaje que incluya el sistema nervioso, los hábitos de descanso, la carga cognitiva y, en muchos casos, cambios concretos en el entorno laboral." },
    ],
  },
  {
    slug: "ciclo-menstrual-senales-de-salud",
    title: "Tu ciclo como brújula: señales que tu período te da sobre tu salud",
    excerpt: "El ciclo menstrual es el quinto signo vital para la mujer. Lo que ves cada mes — la regularidad, el color, el dolor — habla de tu salud hormonal, inmune y metabólica en general.",
    date: "2025-03-04",
    dateFormatted: "4 de marzo de 2025",
    author: "Equipo Organnical",
    authorRole: "Medicina Integrativa",
    category: "Salud Femenina",
    tags: ["ciclo menstrual", "salud femenina", "hormonas", "bienestar"],
    image: u("1571019613454-1cb2f99b2d8b"),
    readTime: 6,
    content: [
      { type: "p", text: "Durante décadas, el ciclo menstrual fue tratado en consulta como un tema incómodo o secundario. Se preguntaba la fecha de la última regla — y hasta ahí. Hoy, la medicina integrativa y la investigación en salud femenina lo ven diferente: el ciclo menstrual es una ventana al estado de salud general de la mujer. Sus cambios son señales, no molestias inevitables." },
      { type: "h2", text: "Qué es un ciclo 'normal' y por qué importa saberlo" },
      { type: "p", text: "Un ciclo saludable tiene entre 21 y 35 días, una duración de 3 a 7 días de sangrado, y un volumen moderado (no tan escaso que apenas mancha ni tan abundante que requiera cambios de protección cada hora). El dolor premenstrual leve es frecuente; el dolor que requiere analgésicos fuertes o que interrumpe actividades no lo es, aunque se normalice." },
      { type: "h2", text: "Señales en el ciclo que merecen atención" },
      { type: "ul", items: [
        "Ciclos muy cortos (menos de 21 días): puede indicar fase lútea insuficiente o reserva ovárica disminuida",
        "Ciclos muy largos o irregulares: frecuentemente asociados con síndrome de ovario poliquístico (SOP)",
        "Sangrado muy abundante (menorragia): puede relacionarse con fibromas, adenomiosis o alteraciones tiroideas",
        "Ausencia de menstruación en ausencia de embarazo: puede indicar hipotiroidismo, amenorrea hipotalámica o SOP",
        "Dolor intenso o incapacitante: endometriosis, adenomiosis o fibromas merecen evaluación",
        "Sangrado entre períodos: siempre merece investigación",
        "Cambios bruscos en el patrón habitual: merecen ser evaluados aunque el nuevo patrón parezca 'normal'",
      ]},
      { type: "quote", text: "Si tu ciclo cambió, tu cuerpo te está diciendo algo. El trabajo médico es escucharlo — no normalizarlo." },
      { type: "h2", text: "El ciclo como espejo hormonal y metabólico" },
      { type: "p", text: "El ciclo menstrual refleja el equilibrio entre estrógenos, progesterona, hormonas tiroideas, insulina y cortisol. Un ciclo irregular o sintomático no es un problema aislado: es una señal de que algo en ese equilibrio merece atención. El estrés crónico puede suprimir la ovulación. El hipotiroidismo puede alargar los ciclos. La resistencia a la insulina puede generar ciclos irregulares con ovarios poliquísticos. Cada patrón tiene una historia." },
      { type: "h2", text: "Cómo usar esta información" },
      { type: "p", text: "Registrar tu ciclo durante 2 o 3 meses — duración, intensidad del sangrado, síntomas asociados y estado de ánimo — es la herramienta más simple y poderosa para entender tu salud hormonal. Esa información, presentada a un médico que sepa leerla, puede orientar una evaluación mucho más precisa que cualquier analítica estándar hecha sin contexto." },
    ],
  },
]

export function getAllSlugs(): string[] {
  return posts.map((p) => p.slug)
}

export function getPost(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug)
}
